
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8500:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      mode: global

  consul1:
    image: "progrium/consul:latest"
    hostname: "consul1"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
    environment:
     - VIRTUAL_HOST=127.0.0.1
     - VIRTUAL_PORT=8500

  consul2:
    image: "progrium/consul:latest"
    hostname: "consul2"
    command: "-server -join consul1"
    depends_on:
      - consul1
    environment:
     - VIRTUAL_HOST=127.0.0.1
     - VIRTUAL_PORT=8500

  consul3:
    image: "progrium/consul:latest"
    hostname: "consul3"
    command: "-server -join consul1"
    depends_on:
      - consul1
    environment:
     - VIRTUAL_HOST=127.0.0.1
     - VIRTUAL_PORT=8500

