
version: '3'

services:

  consul1:
    image: "progrium/consul:latest"
    hostname: "consul1"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
    ports:
      - 8501:8500

  consul2:
    image: "progrium/consul:latest"
    hostname: "consul2"
    command: "-server -join consul1"
    depends_on:
      - consul1
    ports:
      - 8502:8500

  consul3:
    image: "progrium/consul:latest"
    hostname: "consul3"
    command: "-server -join consul1"
    depends_on:
      - consul1

