version: "3"
services:
  web:
    image: nginx:alpine
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:whoami.berndklaus.at"
      replicas: 3
    volumes:
      - nginx-html:/usr/share/nginx/html

networks:
  proxy:
    external: true

volumes:
  nginx-html:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/
