version: '3'

services:
  wordpress:
      image: wordpress
      environment:
        - WORDPRESS_DB_USER=wordpress
        - WORDPRESS_DB_PASSWORD=${PASSWORD}
      expose:
        - "8080/tcp"
      volumes:
        - code:/code
        - html:/var/www/html
      deploy:
        labels:
          - "traefik.port=8080"
          - "traefik.docker.network=proxy"
          - "traefik.frontend.rule=Host:whoami.berndklaus.at"
        replicas: 3
      networks:
        - proxy
        - default

  mariadb:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=${PASSWORD}
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=${PASSWORD}
      volumes:
        - mysql:/var/lib/mysql
      deploy:
        replicas: 1

networks:
  default:
    driver: overlay
  proxy:
    external:
       name: proxy


volumes:
  mysql:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/www/
  code:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/www/
  html:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/www/

